sudo: required
before_install:
  - sudo apt-get install g++ 
  - sudo apt-get install qtdeclarative5-dev
  - sudo apt-get install qtchooser
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc
  
install:

# Build steps
script:
  - mkdir build
  - cd build
  - qtchooser -run-tool=qmake -qt=5 ../qmodbus.pro
  - make -j 8